# docker-compose.yml
version: '3'
services:
  client:
    build: client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules
  server:
    build: server
    ports:
      - 3001:3001
    volumes:
      - ./server:/app
      - /app/node_modules
